export const NEXT_PUBLIC_BODY_OPTIONS = process.env.NEXT_PUBLIC_BODY_OPTIONS;
export const NEXT_PUBLIC_EAR_OPTIONS = process.env.NEXT_PUBLIC_EAR_OPTIONS;
export const NEXT_PUBLIC_FACE_OPTIONS = process.env.NEXT_PUBLIC_FACE_OPTIONS;
export const NEXT_PUBLIC_ENERGY_INCREASE =
  process.env.NEXT_PUBLIC_ENERGY_INCREASE;
export const NEXT_PUBLIC_ENERGY_DECREASE =
  process.env.NEXT_PUBLIC_ENERGY_DECREASE;
export const NEXT_PUBLIC_ENERGY_CAP = process.env.NEXT_PUBLIC_ENERGY_CAP;
